using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using Spritely.Helpers;
using Spritely.Models;

namespace Spritely.Managers
{
    /// <summary>
    /// Queues and persists improvement task suggestions generated by the feedback system.
    /// Tasks are stored as suggestions until the user reviews and launches them.
    /// Persisted to %LOCALAPPDATA%\Spritely\feedback\improvement_queue.json.
    /// </summary>
    public class ImprovementTaskGenerator
    {
        private readonly string _queueFile;
        private readonly object _lock = new();
        private List<ImprovementTaskEntry> _queue = new();

        private static readonly JsonSerializerOptions JsonOptions = new()
        {
            WriteIndented = true,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            PropertyNameCaseInsensitive = true
        };

        /// <summary>Raised when a new improvement task is queued.</summary>
        public event Action<ImprovementTaskEntry>? TaskQueued;

        /// <summary>Returns the current number of pending improvement suggestions.</summary>
        public int PendingCount
        {
            get { lock (_lock) return _queue.Count(t => !t.Dismissed && !t.Launched); }
        }

        public ImprovementTaskGenerator(string appDataDir)
        {
            var feedbackDir = Path.Combine(appDataDir, "feedback");
            Directory.CreateDirectory(feedbackDir);
            _queueFile = Path.Combine(feedbackDir, "improvement_queue.json");
            LoadQueue();
        }

        /// <summary>Adds an improvement suggestion to the queue.</summary>
        public void QueueSuggestion(string projectPath, ImprovementSuggestion suggestion)
        {
            lock (_lock)
            {
                // Skip duplicates by title similarity
                if (_queue.Any(t => !t.Dismissed &&
                    t.Title.Equals(suggestion.Title, StringComparison.OrdinalIgnoreCase) &&
                    t.ProjectPath == projectPath))
                    return;

                var entry = new ImprovementTaskEntry
                {
                    ProjectPath = projectPath,
                    Title = suggestion.Title,
                    Description = suggestion.Description,
                    Category = suggestion.Category,
                    Priority = suggestion.Priority,
                    IsLargeChange = suggestion.IsLargeChange
                };

                _queue.Add(entry);

                // Cap queue size
                if (_queue.Count > 100)
                    _queue = _queue.OrderByDescending(t => t.Priority).Take(100).ToList();

                TaskQueued?.Invoke(entry);
            }

            SaveQueue();
            AppLogger.Info("ImprovementTaskGenerator",
                $"Queued improvement: [{suggestion.Category}] {suggestion.Title} (priority: {suggestion.Priority:F1})");
        }

        /// <summary>Returns all pending (not dismissed, not launched) suggestions.</summary>
        public List<ImprovementTaskEntry> GetPendingSuggestions(string? projectPath = null)
        {
            lock (_lock)
            {
                var q = _queue.Where(t => !t.Dismissed && !t.Launched);
                if (projectPath != null)
                    q = q.Where(t => t.ProjectPath == projectPath);
                return q.OrderByDescending(t => t.Priority).ToList();
            }
        }

        /// <summary>Marks a suggestion as dismissed (user reviewed and rejected).</summary>
        public void Dismiss(string id)
        {
            lock (_lock)
            {
                var entry = _queue.FirstOrDefault(t => t.Id == id);
                if (entry != null) entry.Dismissed = true;
            }
            SaveQueue();
        }

        /// <summary>Marks a suggestion as launched (user created a task from it).</summary>
        public void MarkLaunched(string id)
        {
            lock (_lock)
            {
                var entry = _queue.FirstOrDefault(t => t.Id == id);
                if (entry != null) entry.Launched = true;
            }
            SaveQueue();
        }

        /// <summary>
        /// Builds a task description suitable for launching as an AgentTask from an improvement suggestion.
        /// </summary>
        public static string BuildTaskDescription(ImprovementTaskEntry entry)
        {
            return $"[Feedback Improvement: {entry.Category}] {entry.Title}\n\n" +
                   $"{entry.Description}\n\n" +
                   "This task was auto-generated by the feedback system based on analysis of recent task outcomes. " +
                   "Investigate the issue and implement improvements as appropriate.";
        }

        private void LoadQueue()
        {
            try
            {
                if (!File.Exists(_queueFile)) return;
                var json = File.ReadAllText(_queueFile);
                _queue = JsonSerializer.Deserialize<List<ImprovementTaskEntry>>(json, JsonOptions)
                    ?? new List<ImprovementTaskEntry>();
            }
            catch (Exception ex)
            {
                AppLogger.Warn("ImprovementTaskGenerator", "Failed to load improvement queue", ex);
                _queue = new List<ImprovementTaskEntry>();
            }
        }

        private void SaveQueue()
        {
            try
            {
                List<ImprovementTaskEntry> snapshot;
                lock (_lock)
                {
                    snapshot = _queue.ToList();
                }
                var json = JsonSerializer.Serialize(snapshot, JsonOptions);
                SafeFileWriter.WriteInBackground(_queueFile, json, "ImprovementTaskGenerator");
            }
            catch (Exception ex)
            {
                AppLogger.Warn("ImprovementTaskGenerator", "Failed to save improvement queue", ex);
            }
        }
    }

    /// <summary>
    /// A queued improvement task suggestion with lifecycle tracking.
    /// </summary>
    public class ImprovementTaskEntry
    {
        public string Id { get; set; } = Guid.NewGuid().ToString("N")[..12];
        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public string ProjectPath { get; set; } = "";
        public string Title { get; set; } = "";
        public string Description { get; set; } = "";
        public string Category { get; set; } = "";
        public double Priority { get; set; }
        public bool IsLargeChange { get; set; }
        public bool Dismissed { get; set; }
        public bool Launched { get; set; }
    }
}
